//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiberKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class siber
    {
        public int id { get; set; }
        public string TcNo { get; set; }
        public string adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
    }
}
